baseURL = "https://www.linux.it/~ema/"
languageCode = "en-us"
title = "Emanuele Rocca"
theme = "hugo-theme-zen"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Emanuele Rocca"
    sidebar = false
    description = "A scholar and a gentleman"
    githubUsername = "ema"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = ""
    name = "Writings"
    weight = 1

[[menu.main]]
    url = "talks/"
    name = "Talks"
    weight = 2

[[menu.main]]
    url = "publications/"
    name = "Publications"
    weight = 3

[[menu.main]]
    url = "https://twitter.com/realEmaRocca"
    name = "Twitter"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:ema@linux.it"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ema/"
    name = "github"
    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/emarocca/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/91778/ema"
    name = "stack-overflow"
    weight = 5
